#pragma once

#define IDD_APPLE_MUSIC_PREFS        101
#define IDC_EDIT_DEVELOPER_TOKEN     1001
#define IDC_BUTTON_APPLE_MUSIC_LOGIN 1002
#define IDC_BUTTON_APPLE_MUSIC_SIGN_OUT 1003
#define IDC_STATIC_APPLE_MUSIC_STATUS 1004
#define IDC_STATIC_APPLE_MUSIC_TOKEN 1005

#define IDD_APPLE_MUSIC_LOGIN        201
#define IDC_APPLE_MUSIC_BROWSER      2001
#define IDC_APPLE_MUSIC_LOGIN_STATUS 2002

